/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package banka.otomasyonu;

import static banka.otomasyonu.Kullanici.giris;
import javax.swing.*;

/**
 *
 * @author Sirac
 */
public class GirisYap extends javax.swing.JDialog {

    /**
     * Creates new form GirisYap
     */
    public GirisYap(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(parent);
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        TCYeri = new java.awt.TextField();
        GirisYap = new javax.swing.JButton();
        SifreYeri = new javax.swing.JPasswordField();
        TCLabel = new javax.swing.JLabel();
        tipSec = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/banka/blue-material-material-design-minimal-art-wallpaper-preview.jpg"))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(400, 300));
        getContentPane().setLayout(null);

        TCYeri.setBackground(new java.awt.Color(255, 255, 255));
        TCYeri.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        TCYeri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TCYeriActionPerformed(evt);
            }
        });
        TCYeri.addTextListener(new java.awt.event.TextListener() {
            public void textValueChanged(java.awt.event.TextEvent evt) {
                TCYeriTextValueChanged(evt);
            }
        });
        getContentPane().add(TCYeri);
        TCYeri.setBounds(64, 83, 153, 20);

        GirisYap.setBackground(new java.awt.Color(51, 51, 255));
        GirisYap.setText("Giriş Yap");
        GirisYap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GirisYapActionPerformed(evt);
            }
        });
        getContentPane().add(GirisYap);
        GirisYap.setBounds(90, 170, 110, 23);
        getContentPane().add(SifreYeri);
        SifreYeri.setBounds(65, 133, 152, 22);

        TCLabel.setFont(new java.awt.Font("Segoe UI", 2, 11)); // NOI18N
        TCLabel.setForeground(new java.awt.Color(240, 240, 240));
        TCLabel.setText("TC");
        getContentPane().add(TCLabel);
        TCLabel.setBounds(64, 59, 30, 15);

        tipSec.setBackground(new java.awt.Color(61, 255, 249));
        tipSec.setForeground(new java.awt.Color(0, 0, 255));
        tipSec.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Müşteri", "Personel", "Yönetici" }));
        getContentPane().add(tipSec);
        tipSec.setBounds(270, 83, 90, 22);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 2, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(240, 240, 240));
        jLabel2.setText("Sifre");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(65, 113, 60, 15);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TCYeriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TCYeriActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TCYeriActionPerformed

    private void TCYeriTextValueChanged(java.awt.event.TextEvent evt) {//GEN-FIRST:event_TCYeriTextValueChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_TCYeriTextValueChanged

    private void GirisYapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GirisYapActionPerformed
        // TODO add your handling code here:
        String TC, Sifre;
        if (TCYeri.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Kullanıcı adı boş olamaz", "Hata", JOptionPane.WARNING_MESSAGE);
            return;
        } else {
            TC = TCYeri.getText();
        }
        if (SifreYeri.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Şifre boş olamaz", "Hata", JOptionPane.WARNING_MESSAGE);
            return;
        } else {
            Sifre = SifreYeri.getText();
        }
        if (null != tipSec.getSelectedItem().toString()) switch (tipSec.getSelectedItem().toString()) {
            case "Seçiniz" -> JOptionPane.showMessageDialog(this, "Lütfen kullanıcı tipi seçiniz", "Hata", JOptionPane.WARNING_MESSAGE);
            case "Müşteri" -> {
                boolean durum = giris(TC, Sifre, "Müşteri");
                if (durum == true) {
                    this.dispose();
                    MusteriEkran Mekran = new MusteriEkran(TC,Sifre);
                    Mekran.setVisible(true);
                }                      }
            case "Personel" -> {
                boolean durum = giris(TC, Sifre, "Personel");
                if (durum == true) {
                    this.dispose();
                    PersonelEkran Pekran = new PersonelEkran(TC,Sifre);
                    Pekran.setVisible(true);
                }                      }
            case "Yönetici" -> {
                boolean durum = giris(TC, Sifre, "Yönetici");
                if (durum == true) {
                    this.dispose();
                    YonetimEkran Yekran = new YonetimEkran(TC,Sifre);
                    Yekran.setVisible(true);
                }                      }
            default -> {
            }
        }
    }//GEN-LAST:event_GirisYapActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GirisYap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GirisYap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GirisYap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GirisYap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                GirisYap dialog = new GirisYap(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton GirisYap;
    private javax.swing.JPasswordField SifreYeri;
    private javax.swing.JLabel TCLabel;
    private java.awt.TextField TCYeri;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JComboBox<String> tipSec;
    // End of variables declaration//GEN-END:variables
}
