/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package banka.otomasyonu;

import javax.swing.*;

/**
 *
 * @author Sirac
 */
public class HesapBilgileri extends javax.swing.JDialog {

    Kullanici yeniI = null;

    /**
     * Creates new form HesapBilgileri
     *
     * @param parent
     * @param modal
     * @param yeniI
     */
    public HesapBilgileri(java.awt.Frame parent, boolean modal, Kullanici yeniI) {
        super(parent, modal);
        this.yeniI = yeniI;
        initComponents();
        setLocationRelativeTo(parent);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        IsimLabel = new javax.swing.JLabel();
        SoyIsimLabel = new javax.swing.JLabel();
        TelNoLabel = new javax.swing.JLabel();
        MailLabel = new javax.swing.JLabel();
        TCLabel = new javax.swing.JLabel();
        SifreDegistirButton = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        IsımDegistirButon = new javax.swing.JButton();
        SoyIsımDegistirButon = new javax.swing.JButton();
        TelNoDegistirButon = new javax.swing.JButton();
        MailDegistirButon = new javax.swing.JButton();
        TCDegistirButton = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(64, 113, 147));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 450, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 410, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(51, 51, 255));
        setMaximumSize(new java.awt.Dimension(432, 385));
        setMinimumSize(new java.awt.Dimension(432, 385));
        setPreferredSize(new java.awt.Dimension(432, 385));
        setResizable(false);
        getContentPane().setLayout(null);

        IsimLabel.setText("İsim : "+yeniI.isim);
        getContentPane().add(IsimLabel);
        IsimLabel.setBounds(84, 91, 163, 37);

        SoyIsimLabel.setText("Soyisim : "+yeniI.soyisim);
        getContentPane().add(SoyIsimLabel);
        SoyIsimLabel.setBounds(84, 134, 163, 35);

        TelNoLabel.setText("Telefon No : "+yeniI.telefonNo);
        getContentPane().add(TelNoLabel);
        TelNoLabel.setBounds(84, 175, 163, 37);

        MailLabel.setText("E-posta : "+yeniI.mail);
        getContentPane().add(MailLabel);
        MailLabel.setBounds(84, 218, 163, 35);

        TCLabel.setText("TC : "+yeniI.TC);
        getContentPane().add(TCLabel);
        TCLabel.setBounds(84, 259, 163, 35);

        SifreDegistirButton.setBackground(new java.awt.Color(64, 113, 147));
        SifreDegistirButton.setText("Şifre Değiştir");
        SifreDegistirButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SifreDegistirButtonActionPerformed(evt);
            }
        });
        getContentPane().add(SifreDegistirButton);
        SifreDegistirButton.setBounds(84, 300, 184, 23);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Hesap Bilgileri");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(80, 20, 284, 64);

        IsımDegistirButon.setBackground(new java.awt.Color(64, 113, 147));
        IsımDegistirButon.setText("Değiştir");
        IsımDegistirButon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IsımDegistirButonActionPerformed(evt);
            }
        });
        getContentPane().add(IsımDegistirButon);
        IsımDegistirButon.setBounds(288, 98, 73, 23);

        SoyIsımDegistirButon.setBackground(new java.awt.Color(64, 113, 147));
        SoyIsımDegistirButon.setText("Değiştir");
        SoyIsımDegistirButon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SoyIsımDegistirButonActionPerformed(evt);
            }
        });
        getContentPane().add(SoyIsımDegistirButon);
        SoyIsımDegistirButon.setBounds(288, 140, 73, 23);

        TelNoDegistirButon.setBackground(new java.awt.Color(64, 113, 147));
        TelNoDegistirButon.setText("Değiştir");
        TelNoDegistirButon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TelNoDegistirButonActionPerformed(evt);
            }
        });
        getContentPane().add(TelNoDegistirButon);
        TelNoDegistirButon.setBounds(288, 182, 73, 23);

        MailDegistirButon.setBackground(new java.awt.Color(64, 113, 147));
        MailDegistirButon.setText("Değiştir");
        MailDegistirButon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MailDegistirButonActionPerformed(evt);
            }
        });
        getContentPane().add(MailDegistirButon);
        MailDegistirButon.setBounds(288, 224, 73, 23);

        TCDegistirButton.setBackground(new java.awt.Color(64, 113, 147));
        TCDegistirButton.setText("Değiştir");
        TCDegistirButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TCDegistirButtonActionPerformed(evt);
            }
        });
        getContentPane().add(TCDegistirButton);
        TCDegistirButton.setBounds(288, 265, 73, 23);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SifreDegistirButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SifreDegistirButtonActionPerformed
        // TODO add your handling code here:
        JPasswordField SifreYeri = new JPasswordField(5);
        JPasswordField SifreYeri2 = new JPasswordField(5);
        JPasswordField SifreYeri3 = new JPasswordField(5);

        JPanel myPanel = new JPanel();
        myPanel.add(new JLabel("Mevcut Şifre:"));
        myPanel.add(SifreYeri);
        myPanel.add(Box.createHorizontalStrut(15)); // a spacer
        myPanel.add(new JLabel("Yeni Sifre:"));
        myPanel.add(SifreYeri2);
        myPanel.add(Box.createHorizontalStrut(15)); // a spacer
        myPanel.add(new JLabel("Yeni Sifre Tekrar:"));
        myPanel.add(SifreYeri3);

        int result = JOptionPane.showConfirmDialog(null, myPanel, "Mevcut şifrenizi ve yeni sifrenizi giriniz", JOptionPane.OK_CANCEL_OPTION);
        if (result == JOptionPane.OK_OPTION) {
            if (yeniI.sifre.equals(SifreYeri.getText())) {
                if (SifreYeri2.getText().equals(SifreYeri3.getText())) {
                    yeniI.SifreDegistir(SifreYeri2.getText());
                    JOptionPane.showMessageDialog(this, "Değişiklikleriniz kaydedildi");
                } else {
                    JOptionPane.showMessageDialog(this, "Şifre tekrarı hatalı", "Hata", JOptionPane.WARNING_MESSAGE);
                    return;
                }
            } else {
                JOptionPane.showMessageDialog(this, "Şifreniz yanlış", "Hata", JOptionPane.WARNING_MESSAGE);
                return;
            }
        } else {
            JOptionPane.showMessageDialog(this, "Değişiklikleriniz kaydedilmedi");
        }
    }//GEN-LAST:event_SifreDegistirButtonActionPerformed

    private void TCDegistirButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TCDegistirButtonActionPerformed
        // TODO add your handling code here:
        JPasswordField SifreYeri = new JPasswordField(5);
        JTextField TCYeri = new JTextField(5);

        JPanel myPanel = new JPanel();
        myPanel.add(new JLabel("Şifre:"));
        myPanel.add(SifreYeri);
        myPanel.add(Box.createHorizontalStrut(15)); // a spacer
        myPanel.add(new JLabel("Yeni TC:"));
        myPanel.add(TCYeri);

        int result = JOptionPane.showConfirmDialog(null, myPanel, "Şifrenizi ve yeni TC nizi giriniz", JOptionPane.OK_CANCEL_OPTION);
        if (result == JOptionPane.OK_OPTION) {
            if (yeniI.sifre.equals(SifreYeri.getText())) {
                yeniI.TCDegistir(TCYeri.getText());
                TCLabel.setText("TC : " + yeniI.TC);
                JOptionPane.showMessageDialog(this, "Değişiklikleriniz kaydedildi");
            } else {
                JOptionPane.showMessageDialog(this, "Şifreniz yanlış", "Hata", JOptionPane.WARNING_MESSAGE);
                return;
            }
        } else {
            JOptionPane.showMessageDialog(this, "Değişiklikleriniz kaydedilmedi");
        }
    }//GEN-LAST:event_TCDegistirButtonActionPerformed

    private void IsımDegistirButonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IsımDegistirButonActionPerformed
        // TODO add your handling code here:
        JPasswordField SifreYeri = new JPasswordField(5);
        JTextField IsimYeri = new JTextField(5);

        JPanel myPanel = new JPanel();
        myPanel.add(new JLabel("Şifre:"));
        myPanel.add(SifreYeri);
        myPanel.add(Box.createHorizontalStrut(15)); // a spacer
        myPanel.add(new JLabel("Yeni İsim:"));
        myPanel.add(IsimYeri);

        int result = JOptionPane.showConfirmDialog(null, myPanel, "Şifrenizi ve yeni isminizi giriniz", JOptionPane.OK_CANCEL_OPTION);
        if (result == JOptionPane.OK_OPTION) {
            if (yeniI.sifre.equals(SifreYeri.getText())) {
                yeniI.isim = IsimYeri.getText();
                yeniI.IsımDegistir(IsimYeri.getText());
                IsimLabel.setText("İsim : " + yeniI.isim);
                JOptionPane.showMessageDialog(this, "Değişiklikleriniz kaydedildi");
            } else {
                JOptionPane.showMessageDialog(this, "Şifreniz yanlış", "Hata", JOptionPane.WARNING_MESSAGE);
                return;
            }
        } else {
            JOptionPane.showMessageDialog(this, "Değişiklikleriniz kaydedilmedi");
        }
    }//GEN-LAST:event_IsımDegistirButonActionPerformed

    private void SoyIsımDegistirButonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SoyIsımDegistirButonActionPerformed
        // TODO add your handling code here:
        JPasswordField SifreYeri = new JPasswordField(5);
        JTextField SoyIsimYeri = new JTextField(5);

        JPanel myPanel = new JPanel();
        myPanel.add(new JLabel("Şifre:"));
        myPanel.add(SifreYeri);
        myPanel.add(Box.createHorizontalStrut(15)); // a spacer
        myPanel.add(new JLabel("Yeni Soyisim:"));
        myPanel.add(SoyIsimYeri);

        int result = JOptionPane.showConfirmDialog(null, myPanel, "Şifrenizi ve yeni soyisminizi giriniz", JOptionPane.OK_CANCEL_OPTION);
        if (result == JOptionPane.OK_OPTION) {
            if (yeniI.sifre.equals(SifreYeri.getText())) {
                yeniI.soyisim = SoyIsimYeri.getText();
                yeniI.SoyIsimDegistir(SoyIsimYeri.getText());
                SoyIsimLabel.setText("Soyisim : " + yeniI.soyisim);
                JOptionPane.showMessageDialog(this, "Değişiklikleriniz kaydedildi");
            } else {
                JOptionPane.showMessageDialog(this, "Şifreniz yanlış", "Hata", JOptionPane.WARNING_MESSAGE);
                return;
            }
        } else {
            JOptionPane.showMessageDialog(this, "Değişiklikleriniz kaydedilmedi");
        }
    }//GEN-LAST:event_SoyIsımDegistirButonActionPerformed

    private void TelNoDegistirButonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TelNoDegistirButonActionPerformed
        // TODO add your handling code here:
        JPasswordField SifreYeri = new JPasswordField(5);
        JTextField TelNoYeri = new JTextField(5);

        JPanel myPanel = new JPanel();
        myPanel.add(new JLabel("Şifre:"));
        myPanel.add(SifreYeri);
        myPanel.add(Box.createHorizontalStrut(15)); // a spacer
        myPanel.add(new JLabel("Yeni numara:"));
        myPanel.add(TelNoYeri);

        int result = JOptionPane.showConfirmDialog(null, myPanel, "Şifrenizi ve yeni numaranızı giriniz", JOptionPane.OK_CANCEL_OPTION);
        if (result == JOptionPane.OK_OPTION) {
            if (yeniI.sifre.equals(SifreYeri.getText())) {
                yeniI.telefonNo = TelNoYeri.getText();
                yeniI.TelNoDegistir(TelNoYeri.getText());
                TelNoLabel.setText("Telefon No : " + yeniI.telefonNo);
                JOptionPane.showMessageDialog(this, "Değişiklikleriniz kaydedildi");
            } else {
                JOptionPane.showMessageDialog(this, "Şifreniz yanlış", "Hata", JOptionPane.WARNING_MESSAGE);
                return;
            }
        } else {
            JOptionPane.showMessageDialog(this, "Değişiklikleriniz kaydedilmedi");
        }
    }//GEN-LAST:event_TelNoDegistirButonActionPerformed

    private void MailDegistirButonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MailDegistirButonActionPerformed
        // TODO add your handling code here:
        JPasswordField SifreYeri = new JPasswordField(5);
        JTextField MailYeri = new JTextField(5);

        JPanel myPanel = new JPanel();
        myPanel.add(new JLabel("Şifre:"));
        myPanel.add(SifreYeri);
        myPanel.add(Box.createHorizontalStrut(15)); // a spacer
        myPanel.add(new JLabel("Yeni email:"));
        myPanel.add(MailYeri);

        int result = JOptionPane.showConfirmDialog(null, myPanel, "Şifrenizi ve yeni emailinizi giriniz", JOptionPane.OK_CANCEL_OPTION);
        if (result == JOptionPane.OK_OPTION) {
            if (yeniI.sifre.equals(SifreYeri.getText())) {
                yeniI.mail = MailYeri.getText();
                yeniI.EmailDegistir(MailYeri.getText());
                MailLabel.setText("E-posta : " + yeniI.mail);
                JOptionPane.showMessageDialog(this, "Değişiklikleriniz kaydedildi");
            } else {
                JOptionPane.showMessageDialog(this, "Şifreniz yanlış", "Hata", JOptionPane.WARNING_MESSAGE);
                return;
            }
        } else {
            JOptionPane.showMessageDialog(this, "Değişiklikleriniz kaydedilmedi");
        }
    }//GEN-LAST:event_MailDegistirButonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HesapBilgileri.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HesapBilgileri.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HesapBilgileri.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HesapBilgileri.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel IsimLabel;
    private javax.swing.JButton IsımDegistirButon;
    private javax.swing.JButton MailDegistirButon;
    private javax.swing.JLabel MailLabel;
    private javax.swing.JButton SifreDegistirButton;
    private javax.swing.JLabel SoyIsimLabel;
    private javax.swing.JButton SoyIsımDegistirButon;
    private javax.swing.JButton TCDegistirButton;
    private javax.swing.JLabel TCLabel;
    private javax.swing.JButton TelNoDegistirButon;
    private javax.swing.JLabel TelNoLabel;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
