/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package banka.otomasyonu;

import javax.swing.JOptionPane;

/**
 *
 * @author Sirac
 */
public class KartEkle extends javax.swing.JDialog {
    
    Musteri yeniM = null;
    /**
     * Creates new form KartEkle
     */
    public KartEkle(java.awt.Frame parent, boolean modal,Musteri yeniM) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        this.yeniM = yeniM;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        KartIsmıYeri = new javax.swing.JTextField();
        OlusturButon = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(64, 113, 147));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 260, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 290, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(237, 268));
        setMinimumSize(new java.awt.Dimension(237, 268));
        getContentPane().setLayout(null);

        jLabel1.setText("Kart İsmi");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(60, 95, 60, 16);
        getContentPane().add(KartIsmıYeri);
        KartIsmıYeri.setBounds(60, 115, 115, 22);

        OlusturButon.setBackground(new java.awt.Color(64, 113, 147));
        OlusturButon.setText("Oluştur");
        OlusturButon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OlusturButonActionPerformed(evt);
            }
        });
        getContentPane().add(OlusturButon);
        OlusturButon.setBounds(77, 165, 82, 23);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void OlusturButonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OlusturButonActionPerformed
        // TODO add your handling code here:
        String kartIsım;
        if (KartIsmıYeri.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Kart adı boş olamaz", "Hata", JOptionPane.WARNING_MESSAGE);
            return;
        } else {
            kartIsım = KartIsmıYeri.getText();
        }
        yeniM.kartOluştur(yeniM,kartIsım);
        JOptionPane.showMessageDialog(this,kartIsım+" isimli kartınız oluşturuldu");
        this.dispose();
    }//GEN-LAST:event_OlusturButonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KartEkle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KartEkle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KartEkle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KartEkle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField KartIsmıYeri;
    private javax.swing.JButton OlusturButon;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
