/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package banka.otomasyonu;

import javax.swing.*;

/**
 *
 * @author Sirac
 */
public class Kaydol extends javax.swing.JDialog {

    /**
     * Creates new form Kaydol
     */
    public Kaydol(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel9 = new javax.swing.JLabel();
        Sifre1Yeri = new javax.swing.JPasswordField();
        Sifre2Yeri = new javax.swing.JPasswordField();
        TCYeri = new javax.swing.JTextField();
        SoyadYeri = new javax.swing.JTextField();
        TelefonNoYeri = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        KaydolButton = new javax.swing.JButton();
        tipSec = new javax.swing.JComboBox<>();
        IsımYeri = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        mailYeri = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();

        jLabel9.setForeground(new java.awt.Color(61, 255, 249));
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/banka/65d75f53b8e71bb0c942e50a48445498.png"))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(452, 320));
        setPreferredSize(new java.awt.Dimension(452, 320));
        getContentPane().setLayout(null);

        Sifre1Yeri.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        Sifre1Yeri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Sifre1YeriActionPerformed(evt);
            }
        });
        getContentPane().add(Sifre1Yeri);
        Sifre1Yeri.setBounds(39, 185, 130, 19);

        Sifre2Yeri.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        Sifre2Yeri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Sifre2YeriActionPerformed(evt);
            }
        });
        getContentPane().add(Sifre2Yeri);
        Sifre2Yeri.setBounds(39, 241, 130, 19);

        TCYeri.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        getContentPane().add(TCYeri);
        TCYeri.setBounds(39, 76, 112, 19);

        SoyadYeri.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        getContentPane().add(SoyadYeri);
        SoyadYeri.setBounds(273, 38, 99, 19);

        TelefonNoYeri.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        getContentPane().add(TelefonNoYeri);
        TelefonNoYeri.setBounds(273, 76, 99, 19);

        jLabel1.setForeground(new java.awt.Color(240, 240, 240));
        jLabel1.setText("Şifre");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(39, 160, 50, 16);

        jLabel2.setForeground(new java.awt.Color(240, 240, 240));
        jLabel2.setText("Şifre tekrar");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(39, 216, 80, 16);

        jLabel3.setForeground(new java.awt.Color(240, 240, 240));
        jLabel3.setText("İsim");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(39, 18, 30, 16);

        jLabel4.setForeground(new java.awt.Color(240, 240, 240));
        jLabel4.setText("TC");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(39, 60, 40, 16);

        jLabel5.setForeground(new java.awt.Color(240, 240, 240));
        jLabel5.setText("Soyad");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(273, 18, 51, 16);

        jLabel6.setForeground(new java.awt.Color(240, 240, 240));
        jLabel6.setText("Telefon Numarası");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(273, 60, 90, 16);

        KaydolButton.setBackground(new java.awt.Color(51, 51, 255));
        KaydolButton.setText("Kaydol");
        KaydolButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KaydolButtonActionPerformed(evt);
            }
        });
        getContentPane().add(KaydolButton);
        KaydolButton.setBounds(273, 192, 73, 23);

        tipSec.setBackground(new java.awt.Color(51, 51, 255));
        tipSec.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seçiniz", "Müşteri", "Personel", "Yönetici" }));
        tipSec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipSecActionPerformed(evt);
            }
        });
        getContentPane().add(tipSec);
        tipSec.setBounds(273, 149, 90, 22);

        IsımYeri.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        getContentPane().add(IsımYeri);
        IsımYeri.setBounds(39, 38, 112, 19);

        jLabel7.setForeground(new java.awt.Color(240, 240, 240));
        jLabel7.setText("Kayıt Türü");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(273, 129, 80, 16);

        mailYeri.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        mailYeri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mailYeriActionPerformed(evt);
            }
        });
        getContentPane().add(mailYeri);
        mailYeri.setBounds(39, 122, 112, 19);

        jLabel8.setForeground(new java.awt.Color(240, 240, 240));
        jLabel8.setText("E-posta");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(39, 102, 50, 16);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void KaydolButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KaydolButtonActionPerformed
        // TODO add your handling code here:
        String isim, soyisim, TC, telefonNo, Sifre, mail;
        if (IsımYeri.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "İsim boş olamaz", "Hata", JOptionPane.WARNING_MESSAGE);
            return;
        } else {
            isim = IsımYeri.getText();
        }
        if (SoyadYeri.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Soyisim boş olamaz", "Hata", JOptionPane.WARNING_MESSAGE);
            return;
        } else {
            soyisim = SoyadYeri.getText();
        }
        if (mailYeri.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "E-posta boş olamaz", "Hata", JOptionPane.WARNING_MESSAGE);
            return;
        } else {
            mail = mailYeri.getText();
        }
        if (TCYeri.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "TC boş olamaz", "Hata", JOptionPane.WARNING_MESSAGE);
            return;
        } else {
            TC = TCYeri.getText();
            if (TC.length() != 11) {
                JOptionPane.showMessageDialog(this, "TC 11 haneli olmalıdır", "Hata", JOptionPane.WARNING_MESSAGE);
                return;
            }
        }
        if (TelefonNoYeri.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Kart No boş olamaz", "Hata", JOptionPane.WARNING_MESSAGE);
            return;
        } else {
            telefonNo = TelefonNoYeri.getText();
        }
        if (Sifre1Yeri.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Şifre boş olamaz", "Hata", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if (Sifre2Yeri.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Lütfen şifrenizi Şifre tekrar yerine giriniz", "Hata", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if (!String.valueOf(Sifre1Yeri.getPassword()).equals(String.valueOf(Sifre2Yeri.getPassword()))) {
            JOptionPane.showMessageDialog(this, "Girilen Şifreler birbirleriyle uyuşmuyor", "Hata", JOptionPane.WARNING_MESSAGE);
            return;
        } else {
            Sifre = Sifre1Yeri.getText();
        }
        if (tipSec.getSelectedItem().toString() == "Seçiniz") {
            JOptionPane.showMessageDialog(this, "Lütfen kullanıcı tipi seçiniz", "Hata", JOptionPane.WARNING_MESSAGE);
        } else if (tipSec.getSelectedItem().toString() == "Müşteri") {
            Musteri yeniMusteri = new Musteri(isim, soyisim, TC, telefonNo, Sifre, mail);
            yeniMusteri.kaydol(isim, soyisim, TC, telefonNo, Sifre, mail);
            this.dispose();
        } else if (tipSec.getSelectedItem().toString() == "Personel") {
            Personel yeniPersonel = new Personel(isim, soyisim, TC, telefonNo, Sifre, mail);
            yeniPersonel.kaydol(isim, soyisim, TC, telefonNo, Sifre, mail);
            this.dispose();
        } else if (tipSec.getSelectedItem().toString() == "Yönetici") {
            Yonetici yeniYonetici = new Yonetici(isim, soyisim, TC, telefonNo, Sifre, mail);
            yeniYonetici.kaydol(isim, soyisim, TC, telefonNo, Sifre, mail);
            this.dispose();
        }
        JOptionPane.showMessageDialog(null, "Kayıt olundu");
    }//GEN-LAST:event_KaydolButtonActionPerformed

    private void tipSecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipSecActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tipSecActionPerformed

    private void Sifre1YeriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Sifre1YeriActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Sifre1YeriActionPerformed

    private void mailYeriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mailYeriActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mailYeriActionPerformed

    private void Sifre2YeriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Sifre2YeriActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Sifre2YeriActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Kaydol.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Kaydol.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Kaydol.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Kaydol.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Kaydol dialog = new Kaydol(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField IsımYeri;
    private javax.swing.JButton KaydolButton;
    private javax.swing.JPasswordField Sifre1Yeri;
    private javax.swing.JPasswordField Sifre2Yeri;
    private javax.swing.JTextField SoyadYeri;
    private javax.swing.JTextField TCYeri;
    private javax.swing.JTextField TelefonNoYeri;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField mailYeri;
    private javax.swing.JComboBox<String> tipSec;
    // End of variables declaration//GEN-END:variables
}
