/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package banka.otomasyonu;

import java.awt.Color;
import java.io.BufferedReader;
import java.io.FileReader;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Sirac
 */
public class YonetimEkran extends javax.swing.JFrame {
    Yonetici yeniY = null;
    /**
     * Creates new form YonetimEkran
     */
    public YonetimEkran(String TC, String sifre) {
        try {
            FileReader okuyucu = new FileReader("YöneticiBilgi.txt");
            BufferedReader br = new BufferedReader(okuyucu);
            String satır;
            while ((satır = br.readLine()) != null) {
                String bilgiler[] = new String[7];
                bilgiler = satır.split("/");
                if (TC.equals(bilgiler[2]) && sifre.equals(bilgiler[4])) {
                    yeniY = new Yonetici(bilgiler[0], bilgiler[1], TC, bilgiler[3], sifre, bilgiler[5]);
                }
            }
            okuyucu.close();
            br.close();
        } catch (Exception e) {
            
        }
        initComponents();
        setColor(GirisEkranıPanel);
        GirisEkranıPanel.setOpaque(true);
        resetColor(
            new JPanel[]{PersonelPanel,CikissYapPanel},
            new JPanel[]{PersonelPanel,CikissYapPanel}
        );
        HosgeldinizEkran.setVisible(true);
        PersonelEkran.setVisible(false);
        setLocationRelativeTo(null);
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MenuPanel = new javax.swing.JPanel();
        PersonelPanel = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        GirisEkranıPanel = new javax.swing.JPanel();
        IlkEkranPanel = new javax.swing.JLabel();
        CikissYapPanel = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        HosgeldinizEkran = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        IsımYeri = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        PersonelEkran = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        PersonellerTablo = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(760, 460));
        setMinimumSize(new java.awt.Dimension(760, 460));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        MenuPanel.setBackground(new java.awt.Color(23, 35, 51));
        MenuPanel.setMaximumSize(new java.awt.Dimension(125, 430));
        MenuPanel.setMinimumSize(new java.awt.Dimension(125, 430));

        PersonelPanel.setBackground(new java.awt.Color(41, 57, 80));
        PersonelPanel.setPreferredSize(new java.awt.Dimension(86, 36));
        PersonelPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                PersonelPanelMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                PersonelPanelMouseReleased(evt);
            }
        });

        jLabel4.setForeground(new java.awt.Color(240, 240, 240));
        jLabel4.setText("Personeller");

        javax.swing.GroupLayout PersonelPanelLayout = new javax.swing.GroupLayout(PersonelPanel);
        PersonelPanel.setLayout(PersonelPanelLayout);
        PersonelPanelLayout.setHorizontalGroup(
            PersonelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PersonelPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PersonelPanelLayout.setVerticalGroup(
            PersonelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
        );

        GirisEkranıPanel.setBackground(new java.awt.Color(41, 57, 80));
        GirisEkranıPanel.setPreferredSize(new java.awt.Dimension(86, 36));
        GirisEkranıPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                GirisEkranıPanelMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                GirisEkranıPanelMouseReleased(evt);
            }
        });

        IlkEkranPanel.setForeground(new java.awt.Color(240, 240, 240));
        IlkEkranPanel.setText("Giriş Ekranı");

        javax.swing.GroupLayout GirisEkranıPanelLayout = new javax.swing.GroupLayout(GirisEkranıPanel);
        GirisEkranıPanel.setLayout(GirisEkranıPanelLayout);
        GirisEkranıPanelLayout.setHorizontalGroup(
            GirisEkranıPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, GirisEkranıPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(IlkEkranPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE))
        );
        GirisEkranıPanelLayout.setVerticalGroup(
            GirisEkranıPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(IlkEkranPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
        );

        CikissYapPanel.setBackground(new java.awt.Color(41, 57, 80));
        CikissYapPanel.setPreferredSize(new java.awt.Dimension(86, 36));
        CikissYapPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                CikissYapPanelMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                CikissYapPanelMouseReleased(evt);
            }
        });

        jLabel5.setForeground(new java.awt.Color(240, 240, 240));
        jLabel5.setText("Çıkış Yap");

        javax.swing.GroupLayout CikissYapPanelLayout = new javax.swing.GroupLayout(CikissYapPanel);
        CikissYapPanel.setLayout(CikissYapPanelLayout);
        CikissYapPanelLayout.setHorizontalGroup(
            CikissYapPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CikissYapPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        CikissYapPanelLayout.setVerticalGroup(
            CikissYapPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout MenuPanelLayout = new javax.swing.GroupLayout(MenuPanel);
        MenuPanel.setLayout(MenuPanelLayout);
        MenuPanelLayout.setHorizontalGroup(
            MenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(GirisEkranıPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
            .addComponent(PersonelPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
            .addComponent(CikissYapPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
        );
        MenuPanelLayout.setVerticalGroup(
            MenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuPanelLayout.createSequentialGroup()
                .addGap(142, 142, 142)
                .addComponent(GirisEkranıPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PersonelPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CikissYapPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(228, Short.MAX_VALUE))
        );

        getContentPane().add(MenuPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 490));

        HosgeldinizEkran.setBackground(new java.awt.Color(64, 113, 147));
        HosgeldinizEkran.setMaximumSize(new java.awt.Dimension(760, 460));
        HosgeldinizEkran.setMinimumSize(new java.awt.Dimension(760, 460));
        HosgeldinizEkran.setPreferredSize(new java.awt.Dimension(760, 460));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Hoşgeldiniz");

        IsımYeri.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        IsımYeri.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        IsımYeri.setText(yeniY.isim+" "+yeniY.soyisim);

        jButton2.setText("Hesap Ayarları");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout HosgeldinizEkranLayout = new javax.swing.GroupLayout(HosgeldinizEkran);
        HosgeldinizEkran.setLayout(HosgeldinizEkranLayout);
        HosgeldinizEkranLayout.setHorizontalGroup(
            HosgeldinizEkranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HosgeldinizEkranLayout.createSequentialGroup()
                .addGroup(HosgeldinizEkranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(HosgeldinizEkranLayout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(HosgeldinizEkranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(IsımYeri, javax.swing.GroupLayout.DEFAULT_SIZE, 491, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(HosgeldinizEkranLayout.createSequentialGroup()
                        .addGap(245, 245, 245)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(218, Short.MAX_VALUE))
        );
        HosgeldinizEkranLayout.setVerticalGroup(
            HosgeldinizEkranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HosgeldinizEkranLayout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(IsımYeri, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 109, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(68, 68, 68))
        );

        getContentPane().add(HosgeldinizEkran, new org.netbeans.lib.awtextra.AbsoluteConstraints(121, 0, 640, 490));

        PersonelEkran.setBackground(new java.awt.Color(64, 113, 147));
        PersonelEkran.setMaximumSize(new java.awt.Dimension(760, 460));
        PersonelEkran.setMinimumSize(new java.awt.Dimension(760, 460));
        PersonelEkran.setPreferredSize(new java.awt.Dimension(760, 460));

        PersonellerTablo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "İsim", "Soyisim", "TC", "Telefon", "Mail"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        PersonellerTablo.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        PersonellerTablo.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        PersonellerTablo.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(PersonellerTablo);
        PersonellerTablo.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        if (PersonellerTablo.getColumnModel().getColumnCount() > 0) {
            PersonellerTablo.getColumnModel().getColumn(0).setResizable(false);
            PersonellerTablo.getColumnModel().getColumn(1).setResizable(false);
            PersonellerTablo.getColumnModel().getColumn(2).setResizable(false);
            PersonellerTablo.getColumnModel().getColumn(3).setResizable(false);
            PersonellerTablo.getColumnModel().getColumn(4).setResizable(false);
        }

        jButton1.setText("İşten Çıkar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PersonelEkranLayout = new javax.swing.GroupLayout(PersonelEkran);
        PersonelEkran.setLayout(PersonelEkranLayout);
        PersonelEkranLayout.setHorizontalGroup(
            PersonelEkranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PersonelEkranLayout.createSequentialGroup()
                .addGroup(PersonelEkranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PersonelEkranLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 537, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PersonelEkranLayout.createSequentialGroup()
                        .addGap(252, 252, 252)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(188, Short.MAX_VALUE))
        );
        PersonelEkranLayout.setVerticalGroup(
            PersonelEkranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PersonelEkranLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(48, Short.MAX_VALUE))
        );

        getContentPane().add(PersonelEkran, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 0, 640, 490));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PersonelPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PersonelPanelMousePressed
        // TODO add your handling code here:
        setColor(PersonelPanel);
        personelleriEkle();
        PersonelPanel.setOpaque(true);
        resetColor(
            new JPanel[]{GirisEkranıPanel,CikissYapPanel},
            new JPanel[]{GirisEkranıPanel,CikissYapPanel}
        );
        PersonelEkran.setVisible(true);
        HosgeldinizEkran.setVisible(false);
    }//GEN-LAST:event_PersonelPanelMousePressed

    private void PersonelPanelMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PersonelPanelMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_PersonelPanelMouseReleased

    private void GirisEkranıPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GirisEkranıPanelMousePressed
        // TODO add your handling code here:
        setColor(GirisEkranıPanel);
        GirisEkranıPanel.setOpaque(true);
        resetColor(
            new JPanel[]{PersonelPanel,CikissYapPanel},
            new JPanel[]{PersonelPanel,CikissYapPanel}
        );
        PersonelEkran.setVisible(false);
        HosgeldinizEkran.setVisible(true);
    }//GEN-LAST:event_GirisEkranıPanelMousePressed

    private void GirisEkranıPanelMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GirisEkranıPanelMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_GirisEkranıPanelMouseReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int row;
        DefaultTableModel model = (DefaultTableModel) PersonellerTablo.getModel();
        if (-1 == PersonellerTablo.getSelectedRow()) {
            JOptionPane.showMessageDialog(this, "Lütfen işten çıkarmak istediğiniz personeli seçiniz", "Hata", JOptionPane.WARNING_MESSAGE);
            return;
        }
        else{
            row = PersonellerTablo.getSelectedRow();
        }
        String TC = model.getValueAt(row, 2).toString();
        yeniY.personelIstenCıkar(TC);
        personelleriEkle();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        HesapBilgileri hesap = new HesapBilgileri(this, true, yeniY);
        hesap.setVisible(true);
        IsımYeri.setText(yeniY.isim+" "+yeniY.soyisim);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void CikissYapPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CikissYapPanelMousePressed
        // TODO add your handling code here:
        setColor(CikissYapPanel);
        CikissYapPanel.setOpaque(true);
        resetColor(
            new JPanel[]{PersonelPanel,GirisEkranıPanel},
            new JPanel[]{PersonelPanel,GirisEkranıPanel}
        );
        this.dispose();
        Giris yeniG = new Giris();
        yeniG.setVisible(true);
    }//GEN-LAST:event_CikissYapPanelMousePressed

    private void CikissYapPanelMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CikissYapPanelMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_CikissYapPanelMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(YonetimEkran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(YonetimEkran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(YonetimEkran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(YonetimEkran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
    }

     private void setColor(JPanel pane) {
        pane.setBackground(new Color(41, 57, 80));
    }

    private void resetColor(JPanel[] pane, JPanel[] ind) {
        for (int i = 0; i < pane.length; i++) {
            pane[i].setBackground(new Color(23, 35, 51));
        }
        for (int i = 0; i < ind.length; i++) {
            ind[i].setOpaque(false);
        }
    }
    private void personelleriEkle(){
        try {
            DefaultTableModel model = (DefaultTableModel) PersonellerTablo.getModel();
            model.setRowCount(0);
            FileReader okuyucu = new FileReader("PersonelBilgi.txt");
            BufferedReader br = new BufferedReader(okuyucu);
            String satır;
            while ((satır = br.readLine()) != null) {
                String bilgiler[] = new String[7];
                bilgiler = satır.split("/");
                model.addRow(new Object[]{bilgiler[0],bilgiler[1], bilgiler[2], bilgiler[3], bilgiler[5]});
            }
            okuyucu.close();
            br.close();
        } catch (Exception e) {
            
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CikissYapPanel;
    private javax.swing.JPanel GirisEkranıPanel;
    private javax.swing.JPanel HosgeldinizEkran;
    private javax.swing.JLabel IlkEkranPanel;
    private javax.swing.JLabel IsımYeri;
    private javax.swing.JPanel MenuPanel;
    private javax.swing.JPanel PersonelEkran;
    private javax.swing.JPanel PersonelPanel;
    private javax.swing.JTable PersonellerTablo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
